CREATE TABLE MEMBERS
(
	NUM 		NUMBER			PRIMARY KEY,
	ID			VARCHAR2(100)	NOT NULL,
	PWD 		VARCHAR2(100)	NOT NULL,
	NAME 		VARCHAR2(100)	NOT NULL,
	BIRTH		DATE,
	ISMAN		VARCHAR2(1),
	PHONE 		VARCHAR2(50)	NOT NULL,
	EMAIL 		VARCHAR2(50)	NOT NULL,
	REGDATE 	DATE			DEFAULT SYSDATE,
	ISMEMBER	VARCHAR2(1)		DEFAULT '1'
);